# coding: utf-8

"""
    DUPR Middleware

    Application REST APIs  # noqa: E501

    OpenAPI spec version: v1.0 alpha
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import dupr_backend
from dupr_backend.models.league_standing_response import LeagueStandingResponse  # noqa: E501
from dupr_backend.rest import ApiException


class TestLeagueStandingResponse(unittest.TestCase):
    """LeagueStandingResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLeagueStandingResponse(self):
        """Test LeagueStandingResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dupr_backend.models.league_standing_response.LeagueStandingResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
