# coding: utf-8

"""
    DUPR Middleware

    Application REST APIs  # noqa: E501

    OpenAPI spec version: v1.0 alpha
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import dupr_backend
from dupr_backend.models.single_wrapper_of_player_rating_response import SingleWrapperOfPlayerRatingResponse  # noqa: E501
from dupr_backend.rest import ApiException


class TestSingleWrapperOfPlayerRatingResponse(unittest.TestCase):
    """SingleWrapperOfPlayerRatingResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSingleWrapperOfPlayerRatingResponse(self):
        """Test SingleWrapperOfPlayerRatingResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dupr_backend.models.single_wrapper_of_player_rating_response.SingleWrapperOfPlayerRatingResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
