# coding: utf-8

"""
    DUPR Backend APIs

    Internal RESTful APIs to access DUPR ratings, users and provide matches.

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dupr_backend.models.user_lookup_response import UserLookupResponse

class TestUserLookupResponse(unittest.TestCase):
    """UserLookupResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserLookupResponse:
        """Test UserLookupResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserLookupResponse`
        """
        model = UserLookupResponse()
        if include_optional:
            return UserLookupResponse(
                id = 26518181881,
                referral_code = 'ACASC',
                full_name = 'John Die',
                email = 'john@qwe.com',
                phone_number = '+18938271',
                gender = 'MALE',
                birthdate = '2021-01-13',
                is_valid_email = True,
                is_valid_phone = True,
                image_url = 'https://s3.aws.com/image.png',
                hand = 'LEFT',
                role = dupr_backend.models.role_response.RoleResponse(
                    id = 424255123, 
                    role = 'PLAYER', 
                    permissions = {USER=[VIEW, MODIFY], TOURNAMENT=[OWN_VIEW, OWN_MODIFY, OWN_DELETE]}, ),
                status = 'ACTIVE',
                created = '2021-01-13 01:01:01',
                external_id = 'C12345',
                registered = False,
                restricted = False,
                valid_email = True,
                valid_phone = True
            )
        else:
            return UserLookupResponse(
                full_name = 'John Die',
                email = 'john@qwe.com',
        )
        """

    def testUserLookupResponse(self):
        """Test UserLookupResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
