# coding: utf-8

"""
    DUPR Backend APIs

    Internal RESTful APIs to access DUPR ratings, users and provide matches.

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dupr_backend.models.post_match_rating import PostMatchRating

class TestPostMatchRating(unittest.TestCase):
    """PostMatchRating unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostMatchRating:
        """Test PostMatchRating
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostMatchRating`
        """
        model = PostMatchRating()
        if include_optional:
            return PostMatchRating(
                singles = 1.337,
                doubles = 1.337
            )
        else:
            return PostMatchRating(
        )
        """

    def testPostMatchRating(self):
        """Test PostMatchRating"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
