# coding: utf-8

"""
    DUPR Middleware

    Application REST APIs

    The version of the OpenAPI document: v1.0 alpha
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import dupr_backend
from dupr_backend.models.unclaimed_player_response import UnclaimedPlayerResponse  # noqa: E501
from dupr_backend.rest import ApiException

class TestUnclaimedPlayerResponse(unittest.TestCase):
    """UnclaimedPlayerResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test UnclaimedPlayerResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UnclaimedPlayerResponse`
        """
        model = dupr_backend.models.unclaimed_player_response.UnclaimedPlayerResponse()  # noqa: E501
        if include_optional :
            return UnclaimedPlayerResponse(
                age = 12, 
                claimed = False, 
                fullname = 'Brian Lara', 
                gender = 'MALE/FEMALE', 
                id = 26518181881, 
                image_url = 'http://www.example.com/image.png', 
                ratings = dupr_backend.models.ratings_unclaimed_player_response.RatingsUnclaimedPlayerResponse(
                    doubles = '2.864', 
                    doubles_provisional = False, 
                    doubles_verified = '2.864', 
                    singles = '4.125', 
                    singles_provisional = False, 
                    singles_verified = '4.125', ), 
                referral_code = 'NV3JF2', 
                short_address = '201, San Jose, CA, USA', 
                sponsor = dupr_backend.models.sponsor_logo_response.SponsorLogoResponse(
                    button_text = '', 
                    description = '', 
                    image_url = '', 
                    sponsor_popup_heading = '', 
                    sponsor_redirect_url = '', )
            )
        else :
            return UnclaimedPlayerResponse(
                claimed = False,
                fullname = 'Brian Lara',
                ratings = dupr_backend.models.ratings_unclaimed_player_response.RatingsUnclaimedPlayerResponse(
                    doubles = '2.864', 
                    doubles_provisional = False, 
                    doubles_verified = '2.864', 
                    singles = '4.125', 
                    singles_provisional = False, 
                    singles_verified = '4.125', ),
        )
        """

    def testUnclaimedPlayerResponse(self):
        """Test UnclaimedPlayerResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
