# coding: utf-8

"""
    DUPR Middleware

    Application REST APIs

    The version of the OpenAPI document: v1.0 alpha
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dupr_backend.models.bounds import Bounds

class TestBounds(unittest.TestCase):
    """Bounds unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Bounds:
        """Test Bounds
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Bounds`
        """
        model = Bounds()
        if include_optional:
            return Bounds(
                northeast = dupr_backend.models.lat_lng.LatLng(
                    lat = 1.337, 
                    lng = 1.337, ),
                southwest = dupr_backend.models.lat_lng.LatLng(
                    lat = 1.337, 
                    lng = 1.337, )
            )
        else:
            return Bounds(
        )
        """

    def testBounds(self):
        """Test Bounds"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
