# coding: utf-8

"""
    DUPR Backend APIs

    Internal RESTful APIs to access DUPR ratings, users and provide matches.

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dupr_backend.models.single_wrapper_bracket_club_role_response import SingleWrapperBracketClubRoleResponse

class TestSingleWrapperBracketClubRoleResponse(unittest.TestCase):
    """SingleWrapperBracketClubRoleResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SingleWrapperBracketClubRoleResponse:
        """Test SingleWrapperBracketClubRoleResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SingleWrapperBracketClubRoleResponse`
        """
        model = SingleWrapperBracketClubRoleResponse()
        if include_optional:
            return SingleWrapperBracketClubRoleResponse(
                status = 'SUCCESS',
                message = 'Show this message to user.',
                result = dupr_backend.models.bracket_club_role_response.BracketClubRoleResponse(
                    role_id = 45785789, 
                    role_name = 'ADMIN', 
                    is_club_member = True, 
                    role_name = 'ADMIN', )
            )
        else:
            return SingleWrapperBracketClubRoleResponse(
        )
        """

    def testSingleWrapperBracketClubRoleResponse(self):
        """Test SingleWrapperBracketClubRoleResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
