# coding: utf-8

"""
    DUPR Middleware

    Application REST APIs

    The version of the OpenAPI document: v1.0 alpha
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import dupr_backend
from dupr_backend.models.add_partner_request import AddPartnerRequest  # noqa: E501
from dupr_backend.rest import ApiException

class TestAddPartnerRequest(unittest.TestCase):
    """AddPartnerRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AddPartnerRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddPartnerRequest`
        """
        model = dupr_backend.models.add_partner_request.AddPartnerRequest()  # noqa: E501
        if include_optional :
            return AddPartnerRequest(
                partner_id = 45785789, 
                partner_status = 'NOT_CONFIRMED/INVITED/CONFIRMED/INACTIVE'
            )
        else :
            return AddPartnerRequest(
                partner_id = 45785789,
                partner_status = 'NOT_CONFIRMED/INVITED/CONFIRMED/INACTIVE',
        )
        """

    def testAddPartnerRequest(self):
        """Test AddPartnerRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
