# coding: utf-8

"""
    DUPR Middleware

    Application REST APIs

    The version of the OpenAPI document: v1.0 alpha
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dupr_backend.models.pre_match_rating_and_impact import PreMatchRatingAndImpact

class TestPreMatchRatingAndImpact(unittest.TestCase):
    """PreMatchRatingAndImpact unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PreMatchRatingAndImpact:
        """Test PreMatchRatingAndImpact
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PreMatchRatingAndImpact`
        """
        model = PreMatchRatingAndImpact()
        if include_optional:
            return PreMatchRatingAndImpact(
                match_double_rating_impact_player1 = 1.337,
                match_double_rating_impact_player2 = 1.337,
                match_single_rating_impact_player1 = 1.337,
                match_single_rating_impact_player2 = 1.337,
                pre_match_double_rating_player1 = 1.337,
                pre_match_double_rating_player2 = 1.337,
                pre_match_single_rating_player1 = 1.337,
                pre_match_single_rating_player2 = 1.337
            )
        else:
            return PreMatchRatingAndImpact(
        )
        """

    def testPreMatchRatingAndImpact(self):
        """Test PreMatchRatingAndImpact"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
