# coding: utf-8

"""
    DUPR Middleware

    Application REST APIs  # noqa: E501

    OpenAPI spec version: v1.0 alpha
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import dupr_backend
from dupr_backend.models.team_response import TeamResponse  # noqa: E501
from dupr_backend.rest import ApiException


class TestTeamResponse(unittest.TestCase):
    """TeamResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTeamResponse(self):
        """Test TeamResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dupr_backend.models.team_response.TeamResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
