# coding: utf-8

"""
    DUPR Middleware

    Application REST APIs  # noqa: E501

    OpenAPI spec version: v1.0 alpha
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import dupr_backend
from dupr_backend.api.activity_admin_newsfeeds_features_api import ActivityAdminNewsfeedsFeaturesApi  # noqa: E501
from dupr_backend.rest import ApiException


class TestActivityAdminNewsfeedsFeaturesApi(unittest.TestCase):
    """ActivityAdminNewsfeedsFeaturesApi unit test stubs"""

    def setUp(self):
        self.api = ActivityAdminNewsfeedsFeaturesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_user_suggestions_using_post(self):
        """Test case for add_user_suggestions_using_post

        addUserSuggestions  # noqa: E501
        """
        pass

    def test_create_post_using_post(self):
        """Test case for create_post_using_post

        createPost  # noqa: E501
        """
        pass

    def test_fetch_feeds_using_get(self):
        """Test case for fetch_feeds_using_get

        fetchFeeds  # noqa: E501
        """
        pass

    def test_follow_using_post(self):
        """Test case for follow_using_post

        follow  # noqa: E501
        """
        pass

    def test_get_user_suggestion_using_get(self):
        """Test case for get_user_suggestion_using_get

        getUserSuggestion  # noqa: E501
        """
        pass

    def test_react_using_post(self):
        """Test case for react_using_post

        react  # noqa: E501
        """
        pass

    def test_remove_user_suggestions_using_delete(self):
        """Test case for remove_user_suggestions_using_delete

        removeUserSuggestions  # noqa: E501
        """
        pass

    def test_sync_club_followers_using_post(self):
        """Test case for sync_club_followers_using_post

        syncClubFollowers  # noqa: E501
        """
        pass

    def test_sync_feeds_using_post(self):
        """Test case for sync_feeds_using_post

        syncFeeds  # noqa: E501
        """
        pass

    def test_unfollow_clubs_with_same_ids_using_post(self):
        """Test case for unfollow_clubs_with_same_ids_using_post

        unfollowClubsWithSameIds  # noqa: E501
        """
        pass

    def test_unfollow_using_delete(self):
        """Test case for unfollow_using_delete

        unfollow  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
