# coding: utf-8

"""
    DUPR Middleware

    Application REST APIs  # noqa: E501

    OpenAPI spec version: v1.0 alpha
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import dupr_backend
from dupr_backend.models.edit_partner_request import EditPartnerRequest  # noqa: E501
from dupr_backend.rest import ApiException


class TestEditPartnerRequest(unittest.TestCase):
    """EditPartnerRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEditPartnerRequest(self):
        """Test EditPartnerRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dupr_backend.models.edit_partner_request.EditPartnerRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
