# coding: utf-8

"""
    DUPR Middleware

    Application REST APIs  # noqa: E501

    OpenAPI spec version: v1.0 alpha
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import dupr_backend
from dupr_backend.models.user_preferences_request import UserPreferencesRequest  # noqa: E501
from dupr_backend.rest import ApiException


class TestUserPreferencesRequest(unittest.TestCase):
    """UserPreferencesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserPreferencesRequest(self):
        """Test UserPreferencesRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dupr_backend.models.user_preferences_request.UserPreferencesRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
