# coding: utf-8

"""
    DUPR Middleware

    Application REST APIs  # noqa: E501

    OpenAPI spec version: v1.0 alpha
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import dupr_backend
from dupr_backend.models.single_wrapper_of_page_of_club_member_response import SingleWrapperOfPageOfClubMemberResponse  # noqa: E501
from dupr_backend.rest import ApiException


class TestSingleWrapperOfPageOfClubMemberResponse(unittest.TestCase):
    """SingleWrapperOfPageOfClubMemberResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSingleWrapperOfPageOfClubMemberResponse(self):
        """Test SingleWrapperOfPageOfClubMemberResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dupr_backend.models.single_wrapper_of_page_of_club_member_response.SingleWrapperOfPageOfClubMemberResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
