# coding: utf-8

"""
    DUPR Backend APIs

    Internal RESTful APIs to access DUPR ratings, users and provide matches.

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dupr_backend.models.single_wrapper_role_response import SingleWrapperRoleResponse

class TestSingleWrapperRoleResponse(unittest.TestCase):
    """SingleWrapperRoleResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SingleWrapperRoleResponse:
        """Test SingleWrapperRoleResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SingleWrapperRoleResponse`
        """
        model = SingleWrapperRoleResponse()
        if include_optional:
            return SingleWrapperRoleResponse(
                status = 'SUCCESS',
                message = 'Show this message to user.',
                result = dupr_backend.models.role_response.RoleResponse(
                    id = 424255123, 
                    role = 'PLAYER', 
                    permissions = {USER=[VIEW, MODIFY], TOURNAMENT=[OWN_VIEW, OWN_MODIFY, OWN_DELETE]}, )
            )
        else:
            return SingleWrapperRoleResponse(
        )
        """

    def testSingleWrapperRoleResponse(self):
        """Test SingleWrapperRoleResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
