# coding: utf-8

"""
    DUPR Backend APIs

    Internal RESTful APIs to access DUPR ratings, users and provide matches.

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dupr_backend.api.activity_admin_newsfeeds_features_api import ActivityAdminNewsfeedsFeaturesApi


class TestActivityAdminNewsfeedsFeaturesApi(unittest.TestCase):
    """ActivityAdminNewsfeedsFeaturesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ActivityAdminNewsfeedsFeaturesApi()

    def tearDown(self) -> None:
        pass

    def test_add_user_suggestions(self) -> None:
        """Test case for add_user_suggestions

        """
        pass

    def test_create_post2(self) -> None:
        """Test case for create_post2

        """
        pass

    def test_fetch_feeds2(self) -> None:
        """Test case for fetch_feeds2

        """
        pass

    def test_follow2(self) -> None:
        """Test case for follow2

        """
        pass

    def test_get_user_suggestion(self) -> None:
        """Test case for get_user_suggestion

        """
        pass

    def test_react2(self) -> None:
        """Test case for react2

        """
        pass

    def test_remove_user_suggestions(self) -> None:
        """Test case for remove_user_suggestions

        """
        pass

    def test_sync_club_followers(self) -> None:
        """Test case for sync_club_followers

        """
        pass

    def test_sync_feeds(self) -> None:
        """Test case for sync_feeds

        """
        pass

    def test_unfollow2(self) -> None:
        """Test case for unfollow2

        """
        pass

    def test_unfollow_clubs_with_same_ids(self) -> None:
        """Test case for unfollow_clubs_with_same_ids

        """
        pass


if __name__ == '__main__':
    unittest.main()
