# coding: utf-8

"""
    DUPR Middleware

    Application REST APIs

    The version of the OpenAPI document: v1.0 alpha
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import dupr_backend
from dupr_backend.api.address_api import AddressApi  # noqa: E501
from dupr_backend.rest import ApiException


class TestAddressApi(unittest.TestCase):
    """AddressApi unit test stubs"""

    def setUp(self):
        self.api = dupr_backend.api.address_api.AddressApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_autocomplete_using_get(self):
        """Test case for autocomplete_using_get

        autocomplete  # noqa: E501
        """
        pass

    def test_delete_user_address_using_delete(self):
        """Test case for delete_user_address_using_delete

        deleteUserAddress  # noqa: E501
        """
        pass

    def test_geocode_using_get(self):
        """Test case for geocode_using_get

        geocode  # noqa: E501
        """
        pass

    def test_place_details_using_get(self):
        """Test case for place_details_using_get

        placeDetails  # noqa: E501
        """
        pass

    def test_save_address_using_put(self):
        """Test case for save_address_using_put

        saveAddress  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
