# coding: utf-8

"""
    DUPR Backend APIs

    Internal RESTful APIs to access DUPR ratings, users and provide matches.

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dupr_backend.models.user_auth_provider_request import UserAuthProviderRequest

class TestUserAuthProviderRequest(unittest.TestCase):
    """UserAuthProviderRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserAuthProviderRequest:
        """Test UserAuthProviderRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserAuthProviderRequest`
        """
        model = UserAuthProviderRequest()
        if include_optional:
            return UserAuthProviderRequest(
                facebook = dupr_backend.models.facebook_request.FacebookRequest(
                    token = 'facebook token', ),
                instagram = dupr_backend.models.instagram_request.InstagramRequest(
                    token = 'instagram token', )
            )
        else:
            return UserAuthProviderRequest(
        )
        """

    def testUserAuthProviderRequest(self):
        """Test UserAuthProviderRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
