# coding: utf-8

"""
    DUPR Middleware

    Application REST APIs

    The version of the OpenAPI document: v1.0 alpha
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import dupr_backend
from dupr_backend.models.single_wrapper_of_page_of_open_play_member import SingleWrapperOfPageOfOpenPlayMember  # noqa: E501
from dupr_backend.rest import ApiException

class TestSingleWrapperOfPageOfOpenPlayMember(unittest.TestCase):
    """SingleWrapperOfPageOfOpenPlayMember unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SingleWrapperOfPageOfOpenPlayMember
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SingleWrapperOfPageOfOpenPlayMember`
        """
        model = dupr_backend.models.single_wrapper_of_page_of_open_play_member.SingleWrapperOfPageOfOpenPlayMember()  # noqa: E501
        if include_optional :
            return SingleWrapperOfPageOfOpenPlayMember(
                message = 'Show this message to user.', 
                result = dupr_backend.models.page_of_open_play_member.PageOfOpenPlayMember(
                    empty = False, 
                    has_more = False, 
                    has_previous = True, 
                    hits = [
                        dupr_backend.models.open_play_member.OpenPlayMember(
                            create_at = 'yyyy-MM-dd', 
                            doubles = '', 
                            dupr_id = '', 
                            event_id = 56, 
                            id = 56, 
                            name = '', 
                            singles = '', )
                        ], 
                    limit = 10, 
                    offset = 90, 
                    total = 100, 
                    total_value_relation = 'GREATER_THAN_OR_EQUAL_TO', ), 
                status = 'FAILURE'
            )
        else :
            return SingleWrapperOfPageOfOpenPlayMember(
        )
        """

    def testSingleWrapperOfPageOfOpenPlayMember(self):
        """Test SingleWrapperOfPageOfOpenPlayMember"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
