# coding: utf-8

"""
    DUPR Middleware

    Application REST APIs

    The version of the OpenAPI document: v1.0 alpha
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import dupr_backend
from dupr_backend.models.rating_overview_response import RatingOverviewResponse  # noqa: E501
from dupr_backend.rest import ApiException

class TestRatingOverviewResponse(unittest.TestCase):
    """RatingOverviewResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test RatingOverviewResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RatingOverviewResponse`
        """
        model = dupr_backend.models.rating_overview_response.RatingOverviewResponse()  # noqa: E501
        if include_optional :
            return RatingOverviewResponse(
                all = dupr_backend.models.overview_response.OverviewResponse(
                    all = 10, 
                    losses = 2, 
                    pending = 5, 
                    wins = 3, ), 
                doubles = dupr_backend.models.overview_response.OverviewResponse(
                    all = 10, 
                    losses = 2, 
                    pending = 5, 
                    wins = 3, ), 
                singles = dupr_backend.models.overview_response.OverviewResponse(
                    all = 10, 
                    losses = 2, 
                    pending = 5, 
                    wins = 3, )
            )
        else :
            return RatingOverviewResponse(
                all = dupr_backend.models.overview_response.OverviewResponse(
                    all = 10, 
                    losses = 2, 
                    pending = 5, 
                    wins = 3, ),
                doubles = dupr_backend.models.overview_response.OverviewResponse(
                    all = 10, 
                    losses = 2, 
                    pending = 5, 
                    wins = 3, ),
                singles = dupr_backend.models.overview_response.OverviewResponse(
                    all = 10, 
                    losses = 2, 
                    pending = 5, 
                    wins = 3, ),
        )
        """

    def testRatingOverviewResponse(self):
        """Test RatingOverviewResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
