# coding: utf-8

"""
    DUPR Middleware

    Application REST APIs

    The version of the OpenAPI document: v1.0 alpha
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dupr_backend.models.single_wrapper_of_id_payload import SingleWrapperOfIdPayload

class TestSingleWrapperOfIdPayload(unittest.TestCase):
    """SingleWrapperOfIdPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SingleWrapperOfIdPayload:
        """Test SingleWrapperOfIdPayload
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SingleWrapperOfIdPayload`
        """
        model = SingleWrapperOfIdPayload()
        if include_optional:
            return SingleWrapperOfIdPayload(
                message = 'Show this message to user.',
                result = dupr_backend.models.id_payload.IdPayload(
                    id = 7615704574, ),
                status = 'FAILURE'
            )
        else:
            return SingleWrapperOfIdPayload(
        )
        """

    def testSingleWrapperOfIdPayload(self):
        """Test SingleWrapperOfIdPayload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
