# coding: utf-8

"""
    DUPR Middleware

    Application REST APIs

    The version of the OpenAPI document: v1.0 alpha
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dupr_backend.models.duplicated_player import DuplicatedPlayer

class TestDuplicatedPlayer(unittest.TestCase):
    """DuplicatedPlayer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DuplicatedPlayer:
        """Test DuplicatedPlayer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DuplicatedPlayer`
        """
        model = DuplicatedPlayer()
        if include_optional:
            return DuplicatedPlayer(
                birthday = '',
                dupr_id = '',
                email = '',
                first_name = '',
                full_name = '',
                gender = 'FEMALE',
                hand = 'BOTH',
                id = 56,
                last_name = '',
                status = 'ACTIVE',
                verified_email = True
            )
        else:
            return DuplicatedPlayer(
                id = 56,
                verified_email = True,
        )
        """

    def testDuplicatedPlayer(self):
        """Test DuplicatedPlayer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
