# coding: utf-8

"""
    DUPR Middleware

    Application REST APIs

    The version of the OpenAPI document: v1.0 alpha
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dupr_backend.models.confirm_team_request import ConfirmTeamRequest

class TestConfirmTeamRequest(unittest.TestCase):
    """ConfirmTeamRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConfirmTeamRequest:
        """Test ConfirmTeamRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConfirmTeamRequest`
        """
        model = ConfirmTeamRequest()
        if include_optional:
            return ConfirmTeamRequest(
                bracket_id = 45785789,
                registration_id = 45785789
            )
        else:
            return ConfirmTeamRequest(
                bracket_id = 45785789,
                registration_id = 45785789,
        )
        """

    def testConfirmTeamRequest(self):
        """Test ConfirmTeamRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
