# coding: utf-8

"""
    DUPR Middleware

    Application REST APIs

    The version of the OpenAPI document: v1.0 alpha
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import dupr_backend
from dupr_backend.models.logout_request import LogoutRequest  # noqa: E501
from dupr_backend.rest import ApiException

class TestLogoutRequest(unittest.TestCase):
    """LogoutRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test LogoutRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LogoutRequest`
        """
        model = dupr_backend.models.logout_request.LogoutRequest()  # noqa: E501
        if include_optional :
            return LogoutRequest(
                platform = 'android/ios/webapp', 
                uuid = 'unique-device-identity'
            )
        else :
            return LogoutRequest(
                platform = 'android/ios/webapp',
                uuid = 'unique-device-identity',
        )
        """

    def testLogoutRequest(self):
        """Test LogoutRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
