# coding: utf-8

"""
    DUPR Middleware

    Application REST APIs

    The version of the OpenAPI document: v1.0 alpha
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dupr_backend.models.filters import Filters

class TestFilters(unittest.TestCase):
    """Filters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Filters:
        """Test Filters
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Filters`
        """
        model = Filters()
        if include_optional:
            return Filters(
                is_registered = True,
                is_wait_listed = True,
                partner_status = 'NO_PARTNER',
                payment_status = 'COMPLETE/PENDING',
                registration_status = 'CLOSED'
            )
        else:
            return Filters(
        )
        """

    def testFilters(self):
        """Test Filters"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
