# coding: utf-8

"""
    DUPR Middleware

    Application REST APIs

    The version of the OpenAPI document: v1.0 alpha
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dupr_backend.models.bracket_search_teams_request import BracketSearchTeamsRequest

class TestBracketSearchTeamsRequest(unittest.TestCase):
    """BracketSearchTeamsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BracketSearchTeamsRequest:
        """Test BracketSearchTeamsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BracketSearchTeamsRequest`
        """
        model = BracketSearchTeamsRequest()
        if include_optional:
            return BracketSearchTeamsRequest(
                bracket_id = 7828935307,
                limit = 10,
                offset = 0,
                only_non_wait_listed = False,
                only_wait_listed = False,
                sort = dupr_backend.models.bracket_team_sort.BracketTeamSort(
                    order = 'ASC/DESC', 
                    parameter = 'RATINGS', )
            )
        else:
            return BracketSearchTeamsRequest(
                bracket_id = 7828935307,
                limit = 10,
                offset = 0,
        )
        """

    def testBracketSearchTeamsRequest(self):
        """Test BracketSearchTeamsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
