# coding: utf-8

"""
    DUPR Backend APIs

    Internal RESTful APIs to access DUPR ratings, users and provide matches.

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dupr_backend.models.array_wrapper_mi_lp_team_division import ArrayWrapperMiLPTeamDivision

class TestArrayWrapperMiLPTeamDivision(unittest.TestCase):
    """ArrayWrapperMiLPTeamDivision unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ArrayWrapperMiLPTeamDivision:
        """Test ArrayWrapperMiLPTeamDivision
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ArrayWrapperMiLPTeamDivision`
        """
        model = ArrayWrapperMiLPTeamDivision()
        if include_optional:
            return ArrayWrapperMiLPTeamDivision(
                status = 'SUCCESS',
                message = 'Show this message to user.',
                results = [
                    dupr_backend.models.mi_lp_team_division.MiLPTeamDivision(
                        division_type = 'DUPR12', 
                        teams = [
                            dupr_backend.models.mi_lp_team.MiLPTeam(
                                team_id = 56, 
                                team_code = '', 
                                team_name = '', 
                                status = 'ACTIVE', 
                                created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                team_members = [
                                    dupr_backend.models.team_member.TeamMember(
                                        team_id = 56, 
                                        user_id = 56, 
                                        full_name = '', 
                                        first_name = '', 
                                        last_name = '', 
                                        role = '', 
                                        status = 'ACTIVE', 
                                        created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                        image_url = '', )
                                    ], )
                            ], )
                    ]
            )
        else:
            return ArrayWrapperMiLPTeamDivision(
        )
        """

    def testArrayWrapperMiLPTeamDivision(self):
        """Test ArrayWrapperMiLPTeamDivision"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
