# coding: utf-8

"""
    DUPR Backend APIs

    Internal RESTful APIs to access DUPR ratings, users and provide matches.

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Union
from typing import Optional, Set
from typing_extensions import Self

class BracketRefundRequest(BaseModel):
    """
    BracketRefundRequest
    """ # noqa: E501
    bracket_id: StrictInt = Field(alias="bracketId")
    bracket_name: StrictStr = Field(alias="bracketName")
    registration_id: StrictInt = Field(alias="registrationId")
    process_refund: StrictBool = Field(alias="processRefund")
    withdraw_player: StrictBool = Field(alias="withdrawPlayer")
    refund_amount: Union[StrictFloat, StrictInt] = Field(alias="refundAmount")
    __properties: ClassVar[List[str]] = ["bracketId", "bracketName", "registrationId", "processRefund", "withdrawPlayer", "refundAmount"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BracketRefundRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BracketRefundRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bracketId": obj.get("bracketId"),
            "bracketName": obj.get("bracketName"),
            "registrationId": obj.get("registrationId"),
            "processRefund": obj.get("processRefund"),
            "withdrawPlayer": obj.get("withdrawPlayer"),
            "refundAmount": obj.get("refundAmount")
        })
        return _obj


