# coding: utf-8

"""
    DUPR Middleware

    Application REST APIs

    The version of the OpenAPI document: v1.0 alpha
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr, validator

class DuplicatedPlayer(BaseModel):
    """
    DuplicatedPlayer
    """
    birthday: Optional[StrictStr] = None
    dupr_id: Optional[StrictStr] = Field(None, alias="duprId")
    email: Optional[StrictStr] = None
    first_name: Optional[StrictStr] = Field(None, alias="firstName")
    full_name: Optional[StrictStr] = Field(None, alias="fullName")
    gender: Optional[StrictStr] = None
    hand: Optional[StrictStr] = None
    id: StrictInt = Field(...)
    last_name: Optional[StrictStr] = Field(None, alias="lastName")
    status: Optional[StrictStr] = None
    verified_email: StrictBool = Field(..., alias="verifiedEmail")
    __properties = ["birthday", "duprId", "email", "firstName", "fullName", "gender", "hand", "id", "lastName", "status", "verifiedEmail"]

    @validator('gender')
    def gender_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('FEMALE', 'MALE'):
            raise ValueError("must be one of enum values ('FEMALE', 'MALE')")
        return value

    @validator('hand')
    def hand_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('BOTH', 'LEFT', 'NONE', 'RIGHT'):
            raise ValueError("must be one of enum values ('BOTH', 'LEFT', 'NONE', 'RIGHT')")
        return value

    @validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('ACTIVE', 'CANCELLED', 'COMPLETE', 'CONFIRMED', 'DELETED', 'FORFEITED', 'INACTIVE', 'INVITED', 'IN_PROGRESS', 'MATCH_BYE', 'NOT_CONFIRMED', 'ONGOING', 'PENDING', 'SUSPENDED_TOS_13', 'UPCOMING'):
            raise ValueError("must be one of enum values ('ACTIVE', 'CANCELLED', 'COMPLETE', 'CONFIRMED', 'DELETED', 'FORFEITED', 'INACTIVE', 'INVITED', 'IN_PROGRESS', 'MATCH_BYE', 'NOT_CONFIRMED', 'ONGOING', 'PENDING', 'SUSPENDED_TOS_13', 'UPCOMING')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DuplicatedPlayer:
        """Create an instance of DuplicatedPlayer from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DuplicatedPlayer:
        """Create an instance of DuplicatedPlayer from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DuplicatedPlayer.parse_obj(obj)

        _obj = DuplicatedPlayer.parse_obj({
            "birthday": obj.get("birthday"),
            "dupr_id": obj.get("duprId"),
            "email": obj.get("email"),
            "first_name": obj.get("firstName"),
            "full_name": obj.get("fullName"),
            "gender": obj.get("gender"),
            "hand": obj.get("hand"),
            "id": obj.get("id"),
            "last_name": obj.get("lastName"),
            "status": obj.get("status"),
            "verified_email": obj.get("verifiedEmail")
        })
        return _obj


