# coding: utf-8

"""
    DUPR Middleware

    Application REST APIs

    The version of the OpenAPI document: v1.0 alpha
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictBool, StrictInt

class EditEventTeamRequest(BaseModel):
    """
    EditEventTeamRequest
    """
    bracket_id: StrictInt = Field(..., alias="bracketId")
    club_id: StrictInt = Field(..., alias="clubId")
    is_player1_club_member: StrictBool = Field(..., alias="isPlayer1ClubMember")
    is_player2_club_member: StrictBool = Field(..., alias="isPlayer2ClubMember")
    player1: StrictInt = Field(...)
    player2: StrictInt = Field(...)
    registration_id: StrictInt = Field(..., alias="registrationId")
    __properties = ["bracketId", "clubId", "isPlayer1ClubMember", "isPlayer2ClubMember", "player1", "player2", "registrationId"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> EditEventTeamRequest:
        """Create an instance of EditEventTeamRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> EditEventTeamRequest:
        """Create an instance of EditEventTeamRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return EditEventTeamRequest.parse_obj(obj)

        _obj = EditEventTeamRequest.parse_obj({
            "bracket_id": obj.get("bracketId"),
            "club_id": obj.get("clubId"),
            "is_player1_club_member": obj.get("isPlayer1ClubMember"),
            "is_player2_club_member": obj.get("isPlayer2ClubMember"),
            "player1": obj.get("player1"),
            "player2": obj.get("player2"),
            "registration_id": obj.get("registrationId")
        })
        return _obj


