# coding: utf-8

"""
    DUPR Middleware

    Application REST APIs

    The version of the OpenAPI document: v1.0 alpha
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from typing import Dict, List, Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr, conlist, validator
from dupr_backend.models.attribute import Attribute
from dupr_backend.models.bracket_request import BracketRequest
from dupr_backend.models.league_content_request import LeagueContentRequest

class LeagueRequest(BaseModel):
    """
    LeagueRequest
    """
    additional_information: Optional[LeagueContentRequest] = Field(None, alias="additionalInformation")
    address_id: StrictInt = Field(..., alias="addressId")
    advertise_end: Optional[date] = Field(None, alias="advertiseEnd")
    advertise_start: Optional[date] = Field(None, alias="advertiseStart")
    attributes: Optional[Dict[str, Attribute]] = None
    brackets: Optional[conlist(BracketRequest)] = None
    club_id: StrictInt = Field(..., alias="clubId")
    end_date: date = Field(..., alias="endDate")
    league_id: Optional[StrictInt] = Field(None, alias="leagueId")
    league_name: StrictStr = Field(..., alias="leagueName")
    liability_waiver_id: Optional[StrictInt] = Field(None, alias="liabilityWaiverId")
    long_description: Optional[LeagueContentRequest] = Field(None, alias="longDescription")
    media_id: StrictInt = Field(..., alias="mediaId")
    member_fee: Optional[Union[StrictFloat, StrictInt]] = Field(None, alias="memberFee")
    membership_permission: Optional[StrictStr] = Field(None, alias="membershipPermission")
    non_member_fee: Union[StrictFloat, StrictInt] = Field(..., alias="nonMemberFee")
    refund_policy: Optional[LeagueContentRequest] = Field(None, alias="refundPolicy")
    registration_url: StrictStr = Field(..., alias="registrationUrl")
    safety_policy: Optional[LeagueContentRequest] = Field(None, alias="safetyPolicy")
    short_description: Optional[LeagueContentRequest] = Field(None, alias="shortDescription")
    start_date: date = Field(..., alias="startDate")
    status: Optional[StrictStr] = None
    type: Optional[StrictStr] = None
    user_id: StrictInt = Field(..., alias="userId")
    __properties = ["additionalInformation", "addressId", "advertiseEnd", "advertiseStart", "attributes", "brackets", "clubId", "endDate", "leagueId", "leagueName", "liabilityWaiverId", "longDescription", "mediaId", "memberFee", "membershipPermission", "nonMemberFee", "refundPolicy", "registrationUrl", "safetyPolicy", "shortDescription", "startDate", "status", "type", "userId"]

    @validator('membership_permission')
    def membership_permission_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('CLUB_MEMBERS', 'OPEN_TO_ALL'):
            raise ValueError("must be one of enum values ('CLUB_MEMBERS', 'OPEN_TO_ALL')")
        return value

    @validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('ACTIVE', 'CANCELLED', 'COMPLETE', 'CONFIRMED', 'DELETED', 'FORFEITED', 'INACTIVE', 'INVITED', 'IN_PROGRESS', 'MATCH_BYE', 'NOT_CONFIRMED', 'ONGOING', 'PENDING', 'SUSPENDED_TOS_13', 'UPCOMING'):
            raise ValueError("must be one of enum values ('ACTIVE', 'CANCELLED', 'COMPLETE', 'CONFIRMED', 'DELETED', 'FORFEITED', 'INACTIVE', 'INVITED', 'IN_PROGRESS', 'MATCH_BYE', 'NOT_CONFIRMED', 'ONGOING', 'PENDING', 'SUSPENDED_TOS_13', 'UPCOMING')")
        return value

    @validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('FLEX'):
            raise ValueError("must be one of enum values ('FLEX')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> LeagueRequest:
        """Create an instance of LeagueRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of additional_information
        if self.additional_information:
            _dict['additionalInformation'] = self.additional_information.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each value in attributes (dict)
        _field_dict = {}
        if self.attributes:
            for _key in self.attributes:
                if self.attributes[_key]:
                    _field_dict[_key] = self.attributes[_key].to_dict()
            _dict['attributes'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each item in brackets (list)
        _items = []
        if self.brackets:
            for _item in self.brackets:
                if _item:
                    _items.append(_item.to_dict())
            _dict['brackets'] = _items
        # override the default output from pydantic by calling `to_dict()` of long_description
        if self.long_description:
            _dict['longDescription'] = self.long_description.to_dict()
        # override the default output from pydantic by calling `to_dict()` of refund_policy
        if self.refund_policy:
            _dict['refundPolicy'] = self.refund_policy.to_dict()
        # override the default output from pydantic by calling `to_dict()` of safety_policy
        if self.safety_policy:
            _dict['safetyPolicy'] = self.safety_policy.to_dict()
        # override the default output from pydantic by calling `to_dict()` of short_description
        if self.short_description:
            _dict['shortDescription'] = self.short_description.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> LeagueRequest:
        """Create an instance of LeagueRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return LeagueRequest.parse_obj(obj)

        _obj = LeagueRequest.parse_obj({
            "additional_information": LeagueContentRequest.from_dict(obj.get("additionalInformation")) if obj.get("additionalInformation") is not None else None,
            "address_id": obj.get("addressId"),
            "advertise_end": obj.get("advertiseEnd"),
            "advertise_start": obj.get("advertiseStart"),
            "attributes": dict(
                (_k, Attribute.from_dict(_v))
                for _k, _v in obj.get("attributes").items()
            )
            if obj.get("attributes") is not None
            else None,
            "brackets": [BracketRequest.from_dict(_item) for _item in obj.get("brackets")] if obj.get("brackets") is not None else None,
            "club_id": obj.get("clubId"),
            "end_date": obj.get("endDate"),
            "league_id": obj.get("leagueId"),
            "league_name": obj.get("leagueName"),
            "liability_waiver_id": obj.get("liabilityWaiverId"),
            "long_description": LeagueContentRequest.from_dict(obj.get("longDescription")) if obj.get("longDescription") is not None else None,
            "media_id": obj.get("mediaId"),
            "member_fee": obj.get("memberFee"),
            "membership_permission": obj.get("membershipPermission"),
            "non_member_fee": obj.get("nonMemberFee"),
            "refund_policy": LeagueContentRequest.from_dict(obj.get("refundPolicy")) if obj.get("refundPolicy") is not None else None,
            "registration_url": obj.get("registrationUrl"),
            "safety_policy": LeagueContentRequest.from_dict(obj.get("safetyPolicy")) if obj.get("safetyPolicy") is not None else None,
            "short_description": LeagueContentRequest.from_dict(obj.get("shortDescription")) if obj.get("shortDescription") is not None else None,
            "start_date": obj.get("startDate"),
            "status": obj.get("status"),
            "type": obj.get("type"),
            "user_id": obj.get("userId")
        })
        return _obj


