# coding: utf-8

"""
    DUPR Middleware

    Application REST APIs  # noqa: E501

    OpenAPI spec version: v1.0 alpha
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MatchInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'event_format': 'str',
        'event_name': 'str',
        'match_source': 'str'
    }

    attribute_map = {
        'event_format': 'eventFormat',
        'event_name': 'eventName',
        'match_source': 'matchSource'
    }

    def __init__(self, event_format=None, event_name=None, match_source=None):  # noqa: E501
        """MatchInfo - a model defined in Swagger"""  # noqa: E501
        self._event_format = None
        self._event_name = None
        self._match_source = None
        self.discriminator = None
        self.event_format = event_format
        if event_name is not None:
            self.event_name = event_name
        self.match_source = match_source

    @property
    def event_format(self):
        """Gets the event_format of this MatchInfo.  # noqa: E501


        :return: The event_format of this MatchInfo.  # noqa: E501
        :rtype: str
        """
        return self._event_format

    @event_format.setter
    def event_format(self, event_format):
        """Sets the event_format of this MatchInfo.


        :param event_format: The event_format of this MatchInfo.  # noqa: E501
        :type: str
        """
        if event_format is None:
            raise ValueError("Invalid value for `event_format`, must not be `None`")  # noqa: E501
        allowed_values = ["DOUBLES", "SINGLES"]  # noqa: E501
        if event_format not in allowed_values:
            raise ValueError(
                "Invalid value for `event_format` ({0}), must be one of {1}"  # noqa: E501
                .format(event_format, allowed_values)
            )

        self._event_format = event_format

    @property
    def event_name(self):
        """Gets the event_name of this MatchInfo.  # noqa: E501


        :return: The event_name of this MatchInfo.  # noqa: E501
        :rtype: str
        """
        return self._event_name

    @event_name.setter
    def event_name(self, event_name):
        """Sets the event_name of this MatchInfo.


        :param event_name: The event_name of this MatchInfo.  # noqa: E501
        :type: str
        """

        self._event_name = event_name

    @property
    def match_source(self):
        """Gets the match_source of this MatchInfo.  # noqa: E501


        :return: The match_source of this MatchInfo.  # noqa: E501
        :rtype: str
        """
        return self._match_source

    @match_source.setter
    def match_source(self, match_source):
        """Sets the match_source of this MatchInfo.


        :param match_source: The match_source of this MatchInfo.  # noqa: E501
        :type: str
        """
        if match_source is None:
            raise ValueError("Invalid value for `match_source`, must not be `None`")  # noqa: E501
        allowed_values = ["CLUB", "DUPR", "EXTERNAL", "LEAGUE", "MANUAL", "PARTNER", "TOURNAMENT"]  # noqa: E501
        if match_source not in allowed_values:
            raise ValueError(
                "Invalid value for `match_source` ({0}), must be one of {1}"  # noqa: E501
                .format(match_source, allowed_values)
            )

        self._match_source = match_source

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MatchInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MatchInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
