# coding: utf-8

"""
    DUPR Middleware

    Application REST APIs

    The version of the OpenAPI document: v1.0 alpha
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr

class RatingsUnclaimedPlayerResponse(BaseModel):
    """
    RatingsUnclaimedPlayerResponse
    """
    doubles: Optional[StrictStr] = None
    doubles_provisional: Optional[StrictBool] = Field(None, alias="doublesProvisional")
    doubles_verified: Optional[StrictStr] = Field(None, alias="doublesVerified")
    singles: Optional[StrictStr] = None
    singles_provisional: Optional[StrictBool] = Field(None, alias="singlesProvisional")
    singles_verified: Optional[StrictStr] = Field(None, alias="singlesVerified")
    __properties = ["doubles", "doublesProvisional", "doublesVerified", "singles", "singlesProvisional", "singlesVerified"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> RatingsUnclaimedPlayerResponse:
        """Create an instance of RatingsUnclaimedPlayerResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> RatingsUnclaimedPlayerResponse:
        """Create an instance of RatingsUnclaimedPlayerResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return RatingsUnclaimedPlayerResponse.parse_obj(obj)

        _obj = RatingsUnclaimedPlayerResponse.parse_obj({
            "doubles": obj.get("doubles"),
            "doubles_provisional": obj.get("doublesProvisional"),
            "doubles_verified": obj.get("doublesVerified"),
            "singles": obj.get("singles"),
            "singles_provisional": obj.get("singlesProvisional"),
            "singles_verified": obj.get("singlesVerified")
        })
        return _obj


