# coding: utf-8

"""
    DUPR Middleware

    Application REST APIs

    The version of the OpenAPI document: v1.0 alpha
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from dupr_backend.models.post_match_rating import PostMatchRating
from typing import Optional, Set
from typing_extensions import Self

class TeamPlayer(BaseModel):
    """
    TeamPlayer
    """ # noqa: E501
    allow_substitution: StrictBool = Field(alias="allowSubstitution")
    email: StrictStr
    full_name: StrictStr = Field(alias="fullName")
    id: StrictInt
    image_url: Optional[StrictStr] = Field(default=None, alias="imageUrl")
    post_match_rating: Optional[PostMatchRating] = Field(default=None, alias="postMatchRating")
    referral_code: Optional[StrictStr] = Field(default=None, alias="referralCode")
    status: StrictStr
    validated_match: Optional[StrictBool] = Field(default=None, alias="validatedMatch")
    verified_email: StrictBool = Field(alias="verifiedEmail")
    __properties: ClassVar[List[str]] = ["allowSubstitution", "email", "fullName", "id", "imageUrl", "postMatchRating", "referralCode", "status", "validatedMatch", "verifiedEmail"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['ACTIVE', 'CANCELLED', 'COMPLETE', 'CONFIRMED', 'DELETED', 'FORFEITED', 'INACTIVE', 'INVITED', 'IN_PROGRESS', 'MATCH_BYE', 'NOT_CONFIRMED', 'ONGOING', 'PENDING', 'SUSPENDED_TOS_13', 'UPCOMING']):
            raise ValueError("must be one of enum values ('ACTIVE', 'CANCELLED', 'COMPLETE', 'CONFIRMED', 'DELETED', 'FORFEITED', 'INACTIVE', 'INVITED', 'IN_PROGRESS', 'MATCH_BYE', 'NOT_CONFIRMED', 'ONGOING', 'PENDING', 'SUSPENDED_TOS_13', 'UPCOMING')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TeamPlayer from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of post_match_rating
        if self.post_match_rating:
            _dict['postMatchRating'] = self.post_match_rating.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TeamPlayer from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "allowSubstitution": obj.get("allowSubstitution"),
            "email": obj.get("email"),
            "fullName": obj.get("fullName"),
            "id": obj.get("id"),
            "imageUrl": obj.get("imageUrl"),
            "postMatchRating": PostMatchRating.from_dict(obj["postMatchRating"]) if obj.get("postMatchRating") is not None else None,
            "referralCode": obj.get("referralCode"),
            "status": obj.get("status"),
            "validatedMatch": obj.get("validatedMatch"),
            "verifiedEmail": obj.get("verifiedEmail")
        })
        return _obj


